######################################################################
# Automatically generated by qmake (2.01a) ter mar 19 22:46:22 2013
######################################################################
QT += core gui network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mumuserver.h
SOURCES += main.cpp mumuserver.cpp
