######################################################################
# Automatically generated by qmake (2.01a) dom mar 17 09:43:25 2013
######################################################################
QT += core gui network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += client.h server.h
SOURCES += client.cpp main.cpp server.cpp
