######################################################################
# Automatically generated by qmake (2.01a) ter mar 19 23:26:49 2013
######################################################################
QT += core gui network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mumuclient.h
SOURCES += main.cpp mumuclient.cpp
