######################################################################
# Automatically generated by qmake (2.01a) dom mar 24 21:58:00 2013
######################################################################
QT += core gui network
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mumuclient.h
SOURCES += main.cpp mumuclient.cpp
